{pkgs, ...}: {
  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5 = {
      addons = with pkgs; [
        fcitx5-rime
      ];
    };
  };

  # to update files, delete ./local/share/fcitx5/*
  # comment out home.nix
  # rebuild
  # comment back
  home = {
    file = {
      ".config/fcitx5/conf/classicui.conf" = {
        force = true;
        text = ''
          EnableFractionalScale=True
          Font="BabelStoneHan 12"
          Theme=min
          Vertical Candidate List=True
        '';
      };

      ".local/share/fcitx5/rime/default.custom.yaml" = {
        force = true;
        text = ''
          ---
          patch:
            schema_list:
              - schema: stroke
            menu:
              page_size: 10
        '';
      };

      ".local/share/fcitx5/rime/stroke.custom.yaml" = {
        force = true;
        text = ''
          ---
          import_tables:
            - 李永安
          patch:
            key_binder/bindings:
              - accept: "Control+d"
                send: "BackSpace"
                when: "composing"
              - accept: "Control+j"
                send: "Down"
                when: "composing"
              - accept: "Control+g"
                send: "Escape"
                when: "composing"
              - accept: "Control+h"
                send: "Left"
                when: "composing"
              - accept: "Control+v"
                send: "Page_Down"
                when: "composing"
              - accept: "Control+f"
                send: "Page_Up"
                when: "composing"
              - accept: "Control+l"
                send: "Right"
                when: "composing"
              - accept: "Control+b"
                send: "Shift+Left"
                when: "composing"
              - accept: "Control+e"
                send: "Shift+Right"
                when: "composing"
              - accept: "Control+k"
                send: "Up"
                when: "composing"
            menu:
              page_size: 10
            punctuator/full_shape:
              "!": ["︕"]
              "(": ["︵", "﹁", "︗", "︻", "︹", "﹇", "﹃", "︷"]
              ")": ["︶", "﹂", "︘", "︼", "︺", "﹈", " ﹄", "︸"]
              "*": ["︱", "﹉", "﹊", "﹋", "﹌", "﹍", "﹎", "﹏"]
              ",": ["︐", "﹅", "﹆", "︑"]
              "-": ["︲"]
              ".": ["︒"]
              ":": ["︓"]
              ";": ["︔"]
              "<": ["︽", "︿"]
              ">": ["︾", "﹀"]
              "?": ["︖"]
              "^": ["︙︙"]
              "|": ["︰", "︳", "︴"]
            punctuator/half_shape:
              "!": ["︕"]
              "(": ["︵", "﹁", "︗", "︻", "︹", "﹇", "﹃", "︷"]
              ")": ["︶", "﹂", "︘", "︼", "︺", "﹈", " ﹄", "︸"]
              "*": ["︱", "﹉", "﹊", "﹋", "﹌", "﹍", "﹎", "﹏"]
              ",": ["︐", "﹅", "﹆", "︑"]
              "-": ["︲"]
              ".": ["︒"]
              ":": ["︓"]
              ";": ["︔"]
              "<": ["︽", "︿"]
              ">": ["︾", "﹀"]
              "?": ["︖"]
              "^": ["︙︙"]
              "|": ["︰", "︳", "︴"]
            reverse_lookup/dictionary: 李永安
            translator/dictionary: 李永安

        '';
      };

      ".local/share/fcitx5/themes/min/theme.conf" = {
        force = true;
        text = ''
          [Metadata]
          Name=minimal fcitx5 config
          Version=0.2
          Author=李永安
          Description=follows stylix
          ScaleWithDPI=True
        '';
      };

      # a philippine hokkien / nannang dictionary
      ".local/share/fcitx5/rime/李永安.dict.yaml" = {
        force = true;
        text = ''
          ---
          name: 李永安
          version: "2.0"
          sort: original
          use_preset_vocabulary: true
          max_phrase_length: 1
          ...

          ⼀	h
          ⼁	s
          ⼂	n
          ⼃	p
          ⼄	z

          # TO ADD
          # can take from here and dump to unicodes file
          # BB4HD7LJ.md

          㾪	nhpnhspnpszhhh
          一	hh
          七	hz
          丈	hpn
          三	hhh
          上	shh
          下	hsn
          不	hpsn
          世	hsshz
          个	pns
          中	szhs
          丸	pzn
          久	pzn
          九	pz
          乞	phz
          也	zsz
          乳	pnnpzshz
          了	zs
          予	znzs
          二	hh
          五	hszh
          亞	hshzzhsh
          交	nhpnpn
          人	pn
          仁	pshh
          今	pnnz
          仔	pszsh
          付	pshsn
          代	pshzn
          件	psphhs
          伊	pszhhp
          伯	pspszhh
          伴	psnphhs
          伸	psszhhs
          佇	psnnzhs
          位	psnhnph
          住	psnhhsh
          佗	psnnzpz
          佛	pszhzps
          作	psphshh
          來	hpnpnspn
          係	pspzznspn
          信	psnhhhszh
          修	psspznppp
          俺	pshpnszhhz
          倌	psnnzszhzh
          倒	pshznhshss
          候	psszhphhpn
          倽	pspnhhsszh
          偆	pshhhpnszhh
          假	pszhshhzhzn
          偏	psnzhpszhss
          做	pshsszhphpn
          停	psnhszhnzhs
          偷	pspnhszhhss
          傘	pnpnpnpnpnhs
          備	pshsshpszhhs
          傳	pshszhhshnhsn
          傷	psphszhhhpzpp
          像	pspzszhpzpppn
          僑	psphpnszhszszh
          儂	psszhsshhphhzpn
          允	znpz
          兄	szhpz
          先	phshpz
          光	snphpz
          免	pzszhpz
          入	pn
          內	szpn
          全	nhpshszh
          兩	hszspnpn
          八	pn
          公	pnzn
          六	nhpn
          共	hsshpn
          冊	szssh
          再	hszshh
          准	nhpsnhhhsh
          凊	nhhhshszhh
          凸	hshzh
          出	zsszs
          刀	zp
          分	pnzp
          刣	znszhss
          別	szhzpss
          利	phspnss
          到	hznhshss
          則	szhhhpnss
          剉	pnpnhshss
          前	nphszhhss
          剝	zzhsnhpnss
          剪	nphszhhsszp
          割	nnzhhhsszhss
          創	pnnzhhpszhss
          劃	zhhhshszhshhss
          力	zp
          功	hshzp
          勇	znszhhszp
          動	phszhhshhzp
          勢	hshpnhshpznzp
          包	pzzhz
          北	shhpz
          匙	szhhhshpnpz
          十	hs
          升	phps
          半	nphhs
          印	pzhzs
          卵	pznpzsn
          厚	hpszhhzsh
          厝	hphsshszhh
          去	hshzn
          參	znznznpnppp
          及	pzn
          友	hpzn
          叔	hsshpnzn
          受	pnnpnzz
          叢	ssnphnphhshsshhhzn
          口	szh
          古	hsszh
          叫	szhzs
          可	hszhs
          台	znszh
          吊	szhszs
          同	szhszh
          吐	szhhsh
          向	pszszh
          吱	szhhszn
          吵	szhspnp
          吻	szhpzpp
          吼	szhzshz
          告	phshszh
          呢	szhzhppz
          味	szhhhspn
          命	pnhszhzs
          和	phspnszh
          咖	szhzpszh
          咧	szhhpznss
          咱	szhpszhhh
          哄	szhhsshpn
          哥	hszhshszhs
          哪	szhzhhpzs
          唚	szhzhhnzzn
          唱	szhszhhszhh
          啉	szhhspnhspn
          問	szhhszhhszh
          啡	szhshhhshhh
          啥	szhpnhhsszh
          喔	szhzhphznhsh
          喙	szhzzhpzpppn
          喜	hshszhnphszh
          單	szhszhszhhhs
          嗎	szhhshhsznnnn
          嗐	szhnnzhhhsszh
          嗽	szhhszhspnpzpn
          嘛	szhnhphspnhspn
          器	szhszhhpnnszhszh
          噴	szhhshssszhhhpn
          嚷	szhnhszhszhhhsshpzpn
          囉	szhszsshzznnnnpsnhhhsh
          囊	hszhsnzszhszhhhsshpzsn
          四	szpzh
          囝	szzshh
          回	szszhh
          因	szhpnh
          囥	sznhpzh
          國	szhszhhzpnh
          圖	szszhhsszszhhh
          在	hpshsh
          地	hshzsz
          址	hshshsh
          坐	pnpnhsh
          坦	hshszhhh
          基	hsshhhpnhsh
          堂	snpnzszhhsh
          報	hshnphhszszn
          場	hshszhhhpzpp
          塊	hshpszhhpzzn
          塗	nnhpnhhspnhsh
          墘	hshhsszhhhsph
          壁	zhpszhnhnphhshsh
          外	pznsn
          多	pznpzn
          夠	pznpznpzszh
          大	hpn
          天	hhpn
          奇	hpnhszhs
          女	zph
          好	zphzsh
          妗	zphpnnz
          妹	zphhhspn
          姆	szhzshz
          姊	zphpzsp
          始	zphznszh
          姑	zphhsszh
          姓	zphphhsh
          姨	zphhzhzpn
          娘	zphnzhhzpn
          婆	nnhzpsznzph
          婊	zphhhshpzpn
          婦	zphzhhnzszs
          媠	zphhphshszhh
          媽	zphhshhsznnnn
          子	zsh
          學	pshhpnpnzhhnzzsh
          安	nnzzph
          完	nnzhhpz
          宗	nnzhhspn
          定	nnzhshpn
          害	nnzhhhsszh
          家	nnzhpzpppn
          容	nnzpnpnszh
          寄	nnzhpnhszhs
          密	nnznznpnszs
          寒	nnzhhsshpnnn
          寡	nnzhpszhhhpnzp
          實	nnzzzshszhhhpn
          寫	nnzpshzhhpznnnn
          寶	nnzhhshphhszsszhhhpn
          對	ssnphnphhshhsn
          小	spn
          少	hpn
          尖	spnhpn
          尚	snpszszh
          尺	zhpn
          尻	zhppz
          尾	zhpphhz
          屄	zhpnnzpn
          屎	zhpnphspn
          屜	zhpppshsshz
          山	szs
          川	pss
          巡	zzznzn
          工	hsh
          巧	hshhz
          差	nphhhphsh
          己	zhz
          巴	zshz
          市	nhszs
          希	pnhpszs
          帝	nhnpnzszs
          帶	hpsshznzszs
          常	snpnzszhszs
          幫	hshhshhsnpszhhszs
          平	hnphs
          年	phhshs
          幾	zznzznhpnzpn
          床	nhphspn
          序	nhpznzs
          底	nhppzhzn
          店	nhpshszh
          庭	nhpphshzn
          廁	nhpszhhhpnss
          建	zhhhhszn
          式	hhshzn
          弓	zhz
          弟	npzhzsp
          張	zhzhshhhzpn
          形	hhpsppp
          彩	pnnphspnppp
          彬	hspnhspnppp
          影	szhhnhszhspnppp
          彼	ppszpszn
          待	ppshshhsn
          徊	ppsszszhh
          律	ppszhhhhs
          後	ppszznpzn
          徒	ppshshshpn
          得	ppsszhhhhsn
          徙	ppsshshshpn
          徛	ppshpnhszhs
          從	ppspnpnshpn
          心	nznn
          忽	pzppnznn
          怎	phshhnznn
          思	szhshnznn
          急	pzzhhnznn
          性	nnsphhsh
          怪	nnsznhsh
          恁	psphshnznn
          恨	nnszhhzpn
          情	nnshhshszhh
          想	hspnszhhhnznn
          惶	nnspszhhhhsh
          意	nhnphszhhnznn
          愛	pnnpnznznnpzn
          感	hphszhzpnnznn
          慢	nnsszhhszsshzn
          慣	nnszzshszhhhpn
          慰	zhphhspnhsnnznn
          憑	nhhshhsznnnnnznn
          憢	nnshshhshhshhpz
          應	nhppspsnhhhshnznn
          懸	szhhhhspnpzznspnnznn
          戇	nhnphszhhhspznhshszhhhpnnznn
          我	phshzpn
          截	hshpsnhhhshzpn
          戰	szhszhszhhhshzpn
          戲	shzphzhszhnphhzpn
          房	nzhpnhzp
          所	ppzhpphs
          手	phhs
          批	hshhzpz
          抄	hshspnp
          抉	hshzhpn
          把	hshzshz
          抑	hshpzzs
          投	hshpzzn
          折	hshpphs
          抾	hshhshzn
          抿	hshzhzhz
          拄	hshnhhsh
          拆	hshpphsn
          拇	hshzznhn
          拉	hshnhnph
          拍	hshpszhh
          拖	hshphzsz
          拚	hshznhps
          招	hshzpszh
          拜	phhphhhhs
          拽	hshszhhzp
          挃	hshhznhsh
          指	hshpzszhh
          按	hshnnzzph
          振	hshhphhzpn
          挲	nnhspnpphhs
          挵	hshhhshhps
          捌	hshszhzpss
          捍	hshszhhhhs
          捒	hshhszhspn
          捧	hshhhhpnhhs
          掃	hshzhhnzszs
          掌	snpnzszhphhs
          排	hshshhhshhh
          掛	hshhshhshsn
          掠	hshnhszhspn
          推	hshpsnhhhsh
          揀	hshhsznphspn
          提	hshszhhhshpn
          插	hshphspshzhh
          揕	hshhsshhhpnz
          揣	hshszshpszss
          揭	hshszhhpzpnz
          搬	hshppznhnpzzn
          搭	hshhsspnhszh
          摃	hshhshszhhhpn
          摻	hshznznznpnppp
          摽	hshhszsshhhspn
          撓	 hshhshhshhshhpz
          撚	hshpznnhpnnnnnn
          擔	hshpzhppnnhhhszh
          擠	hshnhnpszppznpshh
          擺	hshszsshznszhhpzpz
          攆	hshhhpnhhpnhszhhhs
          攏	hshnhnphszhhshzhzhhh
          攕	hshpnpnhshhhshhhhzpn
          支	hszn
          收	zsphpn
          放	nhzpphpn
          救	hsnhpnnphpn
          敗	szhhhpnphpn
          教	hshpzshphpn
          敢	zhsshhhphpn
          敲	nhszhszszhshzn
          整	hszhspnphpnhshsh
          數	szhhszhszphphpn
          文	nhpn
          斟	hsshhhpnznnhs
          斡	hsszhhhspnnnhs
          新	nhnphhspnpphs
          日	szhh
          早	szhhhs
          明	szhhpzhh
          易	szhhpzpp
          星	szhhphhsh
          昨	szhhphshh
          是	szhhhshpn
          時	szhhhshhsn
          晏	szhhnnzzph
          晝	zhhhshszhhh
          普	nphssnphszhh
          暗	szhhnhnphszhh
          暝	szhhnzszhhnhpn
          曆	hpphspnphspnszhh
          曉	szhhhshhshhshhpz
          書	zhhhshszhh
          替	hhpnhhpnszhh
          最	szhhhsshhhzn
          會	pnhszsnphszhh
          月	pzhh
          有	hpszhh
          朋	pzhhpzhh
          望	nhzpzhhhhsh
          木	hspn
          本	hspnh
          李	hspnzsh
          杏	hspnszh
          杯	hspnhpsn
          果	szhhhspn
          枝	hspnhszn
          枵	hspnszhhz
          柑	hspnhsshh
          柴	shshpzhspn
          校	hspnnhpnpn
          栽	hshhspnzp
          桌	shszhhhspn
          條	psspznhspn
          梨	phspnsshspn
          椅	hspnhpnhszhs
          椒	hspnshhspnzn
          椰	hspnhsshhhzs
          榴	hspnpznzpszhsh
          槌	hspnpszhzhnzn
          槤	hspnhszhhhsnzn
          樣	hspnnphhshnzzpn
          樹	hspnhshszhnphhsn
          橋	hspnphpnszhszszh
          橙	hspnznppnhszhnph
          機	hspnzznzznhpnzpn
          檢	hspnpnhszhszhpnpn
          檨	hspnnphhshnhnhpzpn
          欠	pzpn
          欱	pnhszhpzpn
          欲	pnpnszhpzpn
          款	hshhhspnpzpn
          歌	hszhshszhspzpn
          歡	hssszhszhpsnhhhshpzpn
          正	hshsh
          步	shshspp
          歪	hpsnhshsh
          歲	shshhphsppzpn
          歹	hpzn
          死	hpznpz
          殕	hpznnhnphszh
          殼	hshnzhpzpzzn
          毋	zzph
          每	phzznhn
          比	hzpz
          毛	phhz
          氣	phhznphspn
          水	szpn
          永	nzzpn
          汁	nnhhs
          汝	nnhzph
          汱	nnhhpnn
          決	nnhzhpn
          河	nnhhszhs
          法	nnhhshzn
          泡	nnhpzzhz
          注	nnhnhhsh
          洗	nnhphshpz
          活	nnhphsszh
          派	nnhpppzpn
          海	nnhphzznhn
          消	nnhsnpszhh
          淡	nnhnppnnppn
          深	nnhnzpnhspn
          淺	nnhhzpnhzpn
          清	nnhhhshszhh
          湯	nnhszhhhpzpp
          滑	nnhszznzszhh
          滲	nnhznznznpnppp
          滷	nnhshszpnnnnnh
          漚	nnhhszhszhszhz
          漢	nnhhsshszhhhpn
          漲	nnhzhzhshhhzpn
          澍	nnhhshszhnphhsn
          澹	nnhpzhppnnhhhszh
          濟	nnhnhnpszppznpshh
          瀉	nnhnnzpshzhhpznnn
          瀾	nnhszhhszhhhsznphspn
          灇	nnhssnphnphhshsshhhzn
          火	nppn
          災	zzznppn
          炒	nppnspnp
          烏	pszhhznnnn
          烘	nppnhsshpn
          無	phhsssshnnnn
          焦	psnhhhshnnnn
          然	pznnhpnnnnnn
          煙	nppnhszsshhsh
          照	szhhzpszhnnnn
          煩	nppnhpszhhhpn
          煮	hshpszhhnnnn
          熄	nppnpszhhhnznn
          熟	nhszhzshpznnnnn
          熱	hshpnhshpznnnnn
          燒	nppnhshhshhshhpz
          燙	nnhszhhhpzppnppn
          爲	pnnppzzznnnn
          爸	pnpnzshz
          爽	hpnpnpnpnpn
          爿	zshp
          牛	phhs
          物	phshpzpp
          特	phshhshhsn
          牽	nhzznnzphhs
          狗	pzppzszh
          猶	pzpnphszpzhh
          王	hhsh
          現	hhshszhhhpz
          球	hhshhsnhpnn
          理	hhshszhhshh
          瓜	ppznn
          瓶	nphhpshzzn
          甘	hsshh
          生	phhsh
          產	nhpnhpphhsh
          用	pzhhs
          田	szhsh
          甲	szhhs
          男	szhshzp
          界	szhshpn
          番	pnphspnszhsh
          畫	zhhhshszhshh
          當	snpnzszhszhsh
          疑	pzphhpnznzshpn
          疼	nhpnhpznnn
          病	nhpnhhszpn
          痣	nhpnhhshnznn
          癖	nhpnhzhpszhnhnphhs
          發	znppnzhzpzzn
          白	pszhh
          百	hpszhh
          皮	zpszn
          盤	ppznhnpzznszssh
          目	szhhh
          相	hspnszhhh
          看	phhpszhhh
          真	hsszhhhhpn
          眩	szhhhnhzzn
          着	nphhhpszhhh
          睏	szhhhszhspnh
          督	shhspnznszhhh
          睭	szhhhpzhshszh
          知	phhpnszh
          短	phhpnhszhnph
          石	hpszh
          破	hpszhzpszn
          碗	hpszhnnzpznzz
          磅	hpszhnhnpnznhzp
          礐	pshhpnpnzhhnzhpszh
          神	nzsnszhhs
          票	hszsshhhspn
          福	nzsnhszhszhsh
          禮	nzsnszhsshhszhnph
          秘	phspnnznpn
          秫	phspnhspnn
          空	nnzpnhsh
          穿	nnzpnhzsp
          窗	nnzpnpszpznh
          竹	phsphs
          笑	phnphnphpn
          第	phnphnzhzsp
          筆	phnphnzhhhhs
          等	phnphnhshhsn
          筍	phnphnpzszhh
          箍	phnphnhshhszsz
          算	phnphnszhhhhps
          管	phnphnnnzszhzh
          箱	phnphnhspnszhhh
          簡	phnphnszhhszhhszhh
          米	nphspn
          粉	nphspnpnzp
          粒	nphspnnhnph
          粽	nphspnnnzhhspn
          糕	nphspnnphhshnnnn
          糖	nphspnnhpzhhsszh
          糜	nhphspnhspnnphspn
          糝	nphspnznznznpnppp
          糞	nphspnszhshhsshpn
          紅	zznnnnhsh
          紙	zznnnnpzhz
          細	zznnnnszhsh
          紲	zznnnnhsshz
          絚	zznnnnhsznnh
          經	zznnnnhzzzhsh
          綠	zznnnnzzhsnhpn
          綴	zznnnnznznznzn
          緊	hszhszznzznspn
          線	zznnnnpszhhszpn
          緝	zznnnnszhhsshhh
          總	zznnnnpszpznhnznn
          續	zznnnnhshzsshszhhhpn
          罕	nzpzhhs
          罪	szsshshhhshhh
          翁	pnznznhznh
          翻	pnphspnszhshznhznh
          老	hshppz
          考	hshphz
          耳	hsshhh
          聲	hshzshppzznhsshhh
          聽	hsshhhhhshhsszsshhnznn
          肉	szpnpn
          肚	pzhhhsh
          股	pzhhpzzn
          肥	pzhhzshz
          肩	nzhpszhh
          肺	pzhhhszs
          胡	hsszhpzhh
          能	znszhhpzpz
          胿	pzhhhshhsh
          脊	nhpnpnszhh
          腔	pzhhnnzpnhsh
          腦	pzhhzzzpszpnh
          腰	pzhhhszsshzph
          腸	pzhhszhhhpzpp
          腹	pzhhphszhhpzn
          腿	pzhhzhhzpnn
          膏	nhszhnzszhszhh
          膚	shzphzszhshszhh
          膣	pzhhnnzpnhznhsh
          臭	pszhhhhpnn
          舅	pshzhhszhshzp
          興	pshhszhszhzhhhpn
          舌	phsszh
          舞	phhsssshpznhzs
          般	ppznhnpzzn
          艱	hsshszhhhpnzhhzpn
          色	pzzshz
          芒	hssnhz
          芥	hsspnps
          芫	hsshhpz
          花	hsspspz
          芳	hssnhzp
          芹	hsspphs
          芽	hsshzsp
          若	hsshpszh
          苦	hsshsszh
          英	hssszhpn
          茶	hsspnhspn
          茹	hsszphszh
          草	hssszhhhs
          荏	hsspsphsh
          荽	hsspnnpzph
          莓	hssphzznhn
          菇	hsszphhsszh
          菊	hsspznphspn
          菜	hsspnnphspn
          華	hsshhsshhs
          菲	hssshhhshhh
          萄	hsspzphhszs
          萬	hssszhhszshn
          落	hssnnhpznszh
          葉	hsshsshzhspn
          葡	hsspzhszhhsn
          蒜	hsshhspnhhspn
          蓋	hsshshznszssh
          蓮	hsshszhhhsnzn
          蔔	hsspzhszhszhsh
          蔗	hssnhphsshnnnn
          蔥	hsspszpzpznhnznn
          蕉	hsspsnhhhshnnnn
          蕹	hssnhzzppsnhhhsh
          薄	hssnnhhszhhsnhsn
          薑	hsshszhshhszhshh
          薯	hssszsshhshpszhh
          薰	hssphsznphshhnnnn
          藍	hsshszhszphnszssh
          蘆	hssshzphzszhshszssh
          蘋	hssshshspphpszhhhpn
          蘿	hssszsshzznnnnpsnhhhsh
          號	szhhzshzphzpz
          虼	szhshnphz
          蚻	hspnzszhshn
          蜷	szhshnnphhpnzz
          蟻	szhshnnphhshphshzpn
          蠅	szhshnszhhszhshhzhh
          行	ppshhs
          術	ppshspnnhhs
          街	ppshshhshhhs
          衝	pphphszhhshhhhs
          表	hhshpzpn
          衫	nzspnppp
          補	nzspnhszhhsn
          裝	zshphshnhpzpn
          褲	nzspnnhphszhhhs
          西	hszpzh
          要	hszsshzph
          規	hhpnszhhhpz
          視	nzsnszhhhpz
          親	nhnphhspnszhhhpz
          覺	pshhpnpnzhhnzszhhhpz
          解	pzpzhhszpphhs
          計	nhhhszhhs
          討	nhhhszhhsn
          記	nhhhszhzhz
          試	nhhhszhhhshzn
          話	nhhhszhphsszh
          詳	nhhhszhnphhhs
          誌	nhhhszhhshnznn
          語	nhhhszhhszhszh
          誠	nhhhszhhpzzpn
          說	nhhhszhpnszhpz
          課	nhhhszhszhhhspn
          調	nhhhszhpzhshszh
          論	nhhhszhpzhszhss
          講	nhhhszhhhsshszshh
          謝	nhhhszhpszhhhphsn
          護	nhhhszhhsspsnhhhshzn
          讀	nhhhszhhshszsshszhhhpn
          變	nhhhszhzznnnnzznnnnphpn
          豆	hszhnph
          豬	hpzpppnhshpszhh
          貌	pnnpzpppszhhpz
          貓	pnnpzpphssszhsh
          貝	szhhhpn
          買	szsshszhhhpn
          費	zhzpsszhhhpn
          賊	szhhhpnhhpzpn
          賓	nnzhsppszhhhpn
          賣	hshszsshszhhhpn
          賺	szhhhpnnphzhhsspn
          贈	szhhhpnnpszsnphszhh
          贏	nhzszhpzhhszhhhpnpzn
          赦	hshpspnphpn
          走	hshshpn
          赴	hshshpnsn
          起	hshshpnzhz
          趕	hshshpnszhhhhs
          趣	hshshpnhsshhhzn
          足	szhshpn
          趺	szhshshhhpn
          跋	szhshshhpznn
          跤	szhshshnhpnpn
          路	szhshshpznszh
          跳	szhshshpnhzpn
          踏	szhshshszpnsszhh
          踮	szhshshnhpshszh
          身	pszhhhp
          軀	pszhhhphszhszhszhz
          車	hszhhhs
          軍	nzhszhhhs
          軟	hszhhhspzpn
          較	hszhhhsnhpnpn
          較	zhhhsnhpnpn
          輪	hszhhhspnhszhss
          轔	hszhhhsnphspnpznhzs
          辦	nhnphhpzpnhnphhs
          迌	pzhhnzn
          迎	pzzsnzn
          近	pphsnzn
          退	zhhzpnnzn
          透	phspnzpnzn
          逐	hpzpppnnz
          這	nhhhszhnzn
          通	znszhhsnzn
          進	psnhhhshnzn
          逼	hszhszhshnzn
          過	szzszszhnzn
          遐	zhshhzhznnzn
          遠	hshszhpspnnzn
          適	nhnpszhsszhnzn
          遮	nhphsshnnnnnzn
          還	szsshhszhpspnnzn
          邊	pszhhhnnzpnnhzpnzn
          邦	hhhpzs
          部	nhnphszhzs
          酌	hszpzhhpzn
          酒	nnhhszpzhh
          酸	hszpzhhznpnpzn
          醉	hszpzhhnhpnpnhs
          醒	hszpzhhszhhphhsh
          醫	hphhpnzpzznhszpzhh
          釋	pnphspnszsshhshnphhs
          重	phszhhshh
          野	szhhshhznzs
          針	pnhhsnphhs
          釣	pnhhsnphpzn
          鉛	pnhhsnphpzszh
          鉸	pnhhsnphnhpnpn
          銀	pnhhsnphzhhzpn
          銃	nnzhpszhhhpnzp
          錢	pnhhsnphhzpnhzpn
          鏡	pnhhsnphnhnphszhhpz
          鐘	pnhhsnphnhnphszhhshh
          鑽	pnhhsnphphshpzphshpzszhhhpn
          鑿	ssnphnphhspshzhhpzznpnhhsnph
          長	hshhhzpn
          門	szhhszhh
          開	szhhszhhhhps
          閒	szhhszhhpzhh
          間	szhhszhhszhh
          閘	szhhszhhszhhs
          閣	szhhszhhpznszh
          關	szhhszhhzznzznzpshs
          阮	zshhpz
          阿	zshszhs
          降	zspznhzs
          陣	zshszhhhs
          陪	zsnhnphszh
          陸	zshshpnhsh
          隊	zsnphpzpppn
          隔	zshszhsznphs
          際	zspznnznhhspn
          隻	psnhhhshzn
          雙	psnhhhshpsnhhhshzn
          雞	pnnpzznhpnpsnhhhsh
          離	nhpnzsszznpsnhhhsh
          雨	hszsnnnn
          雲	hnzsnnnnhhzn
          電	hnzsnnnnszhhz
          霸	hnzsnnnnhsshszhhspzhh
          青	hhshszhh
          靜	hhshszhhpnnpzhhs
          面	hpszsshhh
          鞋	hsshszhhshshhsh
          韓	hsszhhhszshszhhzs
          頂	hshpszhhhpn
          項	hshhpszhhhpn
          頓	hzszhpszhhhpn
          頦	nhzppnhpszhhhpn
          頭	hszhnphhpszhhhpn
          頷	pnnzszhhpszhhhpn
          頸	hzzzhshhpszhhhpn
          題	szhhhshpnhpszhhhpn
          額	nnzpznszhhpszhhhpn
          顧	nzhppsnhhhshhpszhhhpn
          飛	zpnpzpnps
          食	pnnzhhzpn
          飯	pnnzhhznppzn
          飼	pnnzhhznzhszh
          飽	pnnzhhznpzzhz
          飾	pnnzhhznphszs
          餅	pnnzhhznnphhps
          餐	shpznznpnnzhhzpn
          館	pnnzhhznnnzszhzh
          首	nphpszhhh
          香	phspnszhh
          馬	hshhsznnnn
          驚	shhpzszhphpnhshhsznnnn
          骨	szznzszhh
          體	szznzszhhszhsshhszhnph
          高	nhszhszszh
          髡	hshhhznppphpz
          鬚	hshhhznpppppphpszhhhpn
          鬥	hhshshhshs
          鬼	pszhhpzzn
          魚	pzszhshnnnn
          鳥	pszhhhznnnn
          鹹	hshzpnnnnnhhphszhzpn
          鹽	hszhszphshszpnnnnnhszssh
          麗	hsznhsznnhpzsshhzpz
          麭	hspnpnpnpznpzzhz
          麵	hspnpnpnpznhpszsshhh
          麻	nhphspnhspn
          黃	hsshhszhshpn
          點	sznphshhnnnnshszh
          鼻	pszhhhszhshhps
          齒	shshpnpnhpnpnzs
          齩	shshpnpnhpnpnzsnhpnpn
          齻	shshpnpnhpnpnzshsszhhhhpn
          龍	nhnphszhhhzhzhhh
          直	hsszhhhh
          𠕇	hpszn
          𠢕	hshnhzpphpnzp
          𡳞	zhpnphspnpznhzs
          𣍐	pzpppnhszsnphszhh
          𤶃	nhpnhpnhzpn
          𥐵	hpszhhpzz
          𨑨	szhhnzn
          𪜶	psszhpnh
          𫝛	hspnszhhhszhszh

          # BOPOMOFO

          ㄅ	z
          ㆠ	zz
          ㄆ	zn
          ㄇ	sz
          ㄉ	zp
          ㄊ	hzn
          ㄋ	z
          ㄌ	zp
          ㄍ	zz
          ㆣ	zzz
          ㄎ	hz
          ㄫ	hpn
          ㄏ	hp
          ㄐ	zs
          ㆢ	zsz
          ㄑ	z
          ㄒ	hs
          ㄗ	zs
          ㆡ	zsz
          ㄘ	hz
          ㄙ	zn
          ㄚ	nps
          ㆩ	npsz
          ㆦ	hz
          ㆧ	hzz
          ㆤ	zz
          ㆥ	zzz
          ㄞ	hzp
          ㆮ	hzpz
          ㄠ	zzn
          ㆯ	zznz
          ㆰ	npszs
          ㆱ	hzsz
          ㆬ	szs
          ㄢ	zz
          ㄣ	z
          ㄤ	hpn
          ㆲ	hsh
          ㄥ	z
          ㆭ	hpns
          ㄧ	h
          ㆪ	hz
          ㄨ	pn
          ㆫ	pnz
          ˆ	pn
          ˫	sh
          ˊ	h
          ˋ	n
          ˙	n
          ㆴ	z
          ㆵ	zp
          ㆻ	zz
          ㆷ	hp
        '';
      };
    };
  };
}
